#ifndef __GF_ERROR_H__
#define __GF_ERROR_H__

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum gf_error {
    GF_SUCCESS = 0,

    //ta error
    GF_ERROR_BASE = 1000,
    GF_ERROR_OUT_OF_MEMORY = GF_ERROR_BASE + 1,
    GF_ERROR_OPEN_TA_FAILED = GF_ERROR_BASE + 2,
    GF_ERROR_BAD_PARAMS = GF_ERROR_BASE + 3,
    GF_ERROR_NO_SPACE = GF_ERROR_BASE + 4,
    GF_ERROR_REACH_FINGERS_UPLIMIT = GF_ERROR_BASE + 5,
    GF_ERROR_NOT_MATCH = GF_ERROR_BASE + 6,
    GF_ERROR_CANCELED = GF_ERROR_BASE + 7,
    GF_ERROR_TIMEOUT = GF_ERROR_BASE + 8,
    GF_ERROR_PREPROCESS_FAILED = GF_ERROR_BASE + 9,
    GF_ERROR_GENERIC = GF_ERROR_BASE + 10,
    GF_ERROR_ACQUIRED_PARTIAL = GF_ERROR_BASE + 11,
    GF_ERROR_ACQUIRED_IMAGER_DIRTY = GF_ERROR_BASE + 12,
    GF_ERROR_DUPLICATE_FINGER = GF_ERROR_BASE + 13,
    GF_ERROR_OPEN_DEVICE_FAILED = GF_ERROR_BASE + 14,
    GF_ERROR_HAL_GENRAL_ERROR = GF_ERROR_BASE + 15,
    GF_ERROR_HAL_FILE_DESCRIPTION_NULL = GF_ERROR_BASE + 16,
    GF_ERROR_HAL_IOCTL_FAILED = GF_ERROR_BASE + 17,
    GF_ERROR_HAL_TIMER_FUNC = GF_ERROR_BASE + 18,
    GF_ERROR_CORRUPT_CONTENT = GF_ERROR_BASE + 19,
    GF_ERROR_INCORRECT_VERSION = GF_ERROR_BASE + 20,
    GF_ERROR_CORRUPT_OBJECT = GF_ERROR_BASE + 21,
    GF_ERROR_INVALID_DATA = GF_ERROR_BASE + 22,
    GF_ERROR_SPI_TRANSFER_ERROR = GF_ERROR_BASE + 23,
    GF_ERROR_SPI_GENERAL_ERROR = GF_ERROR_BASE + 24,
    GF_ERROR_SPI_IRQ_HANDLE = GF_ERROR_BASE + 25,
    GF_ERROR_SPI_RAW_DATA_CRC_FAILED = GF_ERROR_BASE + 26,
    GF_ERROR_SPI_RAW_DATA_BUF_BUSY = GF_ERROR_BASE + 27,
    GF_ERROR_SPI_FW_CFG_DATA_ERROR = GF_ERROR_BASE + 28,
    GF_ERROR_SPI_FW_DOWNLOAD_FAILED = GF_ERROR_BASE + 29,
    GF_ERROR_SPI_CFG_DOWNLOAD_FAILED = GF_ERROR_BASE + 30,
    GF_ERROR_SAVE_FP_TEMPLATE = GF_ERROR_BASE + 31,
    GF_ERROR_FP_BUSY = GF_ERROR_BASE + 32,
    GF_ERROR_OPEN_SECURE_OBJECT_FAILED = GF_ERROR_BASE + 33,
    GF_ERROR_READ_SECURE_OBJECT_FAILED = GF_ERROR_BASE + 34,
    GF_ERROR_WRITE_SECURE_OBJECT_FAILED = GF_ERROR_BASE + 35,
    GF_ERROR_SECURE_OBJECT_NOT_EXIST = GF_ERROR_BASE + 36,
    GF_ERROR_WRITE_CONFIG_FAILED = GF_ERROR_BASE + 39,
    GF_ERROR_TEST_SENSOR_FAILED = GF_ERROR_BASE + 40,
    GF_ERROR_SET_MODE_FAILED = GF_ERROR_BASE + 41,
    GF_ERROR_CHIPID_NOT_CORRECT = GF_ERROR_BASE + 42,
    GF_ERROR_MAX_NUM = GF_ERROR_BASE + 43,
    GF_ERROR_TEST_BAD_POINT_FAILED = GF_ERROR_BASE + 44,
    GF_ERROR_TEST_FRR_FAR_ENROLL_DIFFERENT_FINGER = GF_ERROR_BASE + 45,
    GF_ERROR_DUPLICATE_AREA = GF_ERROR_BASE + 46,
    GF_ERROR_SPI_COMMUNICATION = GF_ERROR_BASE + 47,
    GF_ERROR_FINGER_NOT_EXIST = GF_ERROR_BASE + 48,
    GF_ERROR_INVALID_PREPROCESS_VERSION = GF_ERROR_BASE + 49, ///< This means the saved preprocess version is
    ///< different from the new preprocess version.
    ///< Should delete the saved calibration parameters.
    GF_ERROR_TA_DEAD = GF_ERROR_BASE + 50,
    GF_ERROR_NAV_TOO_FAST = GF_ERROR_BASE + 51,
    GF_ERROR_UNSUPPORT_SENSOR = GF_ERROR_BASE + 52,
    GF_ERROR_INVALID_FINGER_PRESS = GF_ERROR_BASE + 53, // Means that finger press event is caused by temperature, should update all base
    GF_ERROR_TA_GENERATE_RANDOM = GF_ERROR_BASE + 54,
    GF_ERROR_BIO_ASSAY_FAIL = GF_ERROR_BASE + 55,
    GF_ERROR_INVALID_HAT_VERSION = GF_ERROR_BASE + 56,
    GF_ERROR_INVALID_CHALLENGE = GF_ERROR_BASE + 57,
    GF_ERROR_UNTRUSTED_ENROLL = GF_ERROR_BASE + 58,
    GF_ERROR_INVALID_BASE_FRAME_DATA = GF_ERROR_BASE + 59,

    GF_ERROR_SENSOR_BROKEN_CHECK_NEXT_FRAME = GF_ERROR_BASE + 60,
    GF_ERROR_SENSOR_BROKEN_CHECK_ALGO_ERROR = GF_ERROR_BASE + 61,
    GF_ERROR_SENSOR_IS_BROKEN = GF_ERROR_BASE + 62,

    //native service error
    GF_ERROR_NATIVE_SERVICE_BASE = 2000,
    GF_ERROR_NATIVE_SERVICE_GETSERVICE = GF_ERROR_NATIVE_SERVICE_BASE + 1,
    GF_ERROR_NATIVE_SERVICE_INIT_HAL = GF_ERROR_NATIVE_SERVICE_BASE + 2,

    GF_ERROR_MAX = 3000,
} gf_error_t;

#ifdef __cplusplus
}
#endif

#endif // __GF_ERROR_H__
